accounts/urls.py
from . import views
from django.urls import path
app_name = 'accounts'
urlpatterns = [
    path('register', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout', views.logout, name='logout'),
]

todo_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

todoapp/urls.py
from django.urls import path

from todoapp import views

app_name = 'todoapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('update/<int:id>/', views.update, name='update'),
    path('cbvhome/', views.Tasklistview.as_view(), name='cbvhome'),
    path('cbvdetail/<int:pk>/', views.taskDetailview.as_view(), name='cbvdetail'),
    path('cbvupdate/<int:pk>/', views.taskupdateview.as_view(), name='cbvupdate'),
    path('cbvdelete/<int:pk>/', views.Taskkdeleteview.as_view(), name='cbvdelete')
]

accounts/models.py
from django.db import models

# Create your models here.

todoapp/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
    username = models.CharField(max_length=200,default="js")
    name = models.CharField(max_length=200)
    priority = models.IntegerField()
    date = models.DateField()

    def __str__(self):
        return self.name

todoapp/forms.py
from .models import Task
from django import forms

class Todoform(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'priority', 'date']

accounts/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
def logout(request):
    auth.logout(request)
    return redirect('accounts:login')


def register(request):
    if request.method == 'POST':
        un = request.POST['user_name']
        fn = request.POST['first_name']
        ln = request.POST['last_name']
        email = request.POST['email_id']
        password = request.POST['pass1']
        cpassword = request.POST['pass2']
        if User.objects.filter(username=un).exists():
            messages.info(request, "Username already taken")
            return redirect('accounts:register')
        elif User.objects.filter(email=email).exists():
            messages.info(request, "email already taken")
            return redirect('accounts:register')
        elif password == cpassword:
            user = User.objects.create_user(username=un, email=email, first_name=fn, last_name=ln, password=password)
            user.save()
            print("user created")
        else:
            messages.info(request, "password don't match")
            return redirect('accounts:register')
        return redirect('accounts:login')
    return render(request, 'registration/register.html')


def login(request):
    if request.method == 'POST':
        uname = request.POST['uname']
        password = request.POST['password']
        user = auth.authenticate(username=uname, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, "invalid user")
            return redirect('accounts:login')
    return render(request, 'registration/login.html')

todoapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from todoapp.forms import Todoform
from todoapp.models import Task
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView


class Taskkdeleteview(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('todoapp:cbvhome')


class taskupdateview(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('name', 'priority', 'date')

    def get_success_url(self):
        return reverse_lazy('todoapp:cbvdetail',kwargs={'pk': self.object.id})


class taskDetailview(DetailView):
    model = Task
    template_name = 'detail.html'
    context_object_name = 'task'


class Tasklistview(ListView):
    model = Task
    template_name = 'index.html'
    context_object_name = 'task'


# Create your views here.
@login_required
def index(request):
    username = request.user.username
    taskAll = Task.objects.all().filter(username=username)
    if request.method == 'POST':
        un = request.POST.get('username')
        name = request.POST.get('task')
        priority = request.POST.get('priority')
        date = request.POST.get('date')
        newtask = Task(username=un, name=name, priority=priority, date=date)
        newtask.save()
    print(username)
    return render(request, 'index.html', {'task': taskAll})

@login_required
def delete(request, id):
    taskdone = Task.objects.get(id=id)
    if request.method == 'POST':
        taskdone.delete()
        return redirect('/')
    return render(request, 'delete.html')

@login_required
def update(request, id):
    task = Task.objects.get(id=id)
    f = Todoform(request.POST or None, instance=task)
    if f.is_valid():
        f.save()
        return redirect('/')
    return render(request, 'edit.html', {'f': f, 'task': task})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="banner d-flex align-items-center justify-content-center">
      <div class="banner-text text-danger"><h2>ToDo</h2></div>
        <span style="position:absolute; right:5px">
            {% if user.is_authenticated %}
            <p class="text text-white m-2" style="display: inline;">Hi {{user.username}}...</p>
            <a href="{% url 'accounts:logout' %}"><button class="btn btn-info">Logout</button></a>
            {% else %}
            <p class="text text-white m-2" style="display: inline;">Hi.. Please Login</p>
            <a href="{% url 'accounts:register' %}"><button class="btn btn-info">Register</button></a>>
            <a href="{% url 'accounts:login' %}"><button class="btn btn-info">Login</button></a>>
            {% endif %}
        </span>
    </div>

  </div>
</div>
{% block body %}

{% endblock %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/delete.html
{% extends 'base.html' %}
{% block body %}

<form method="post">
    {% csrf_token %}
    <p>Are you sure want to delete?</p>
    <input type="submit">

</form>



{% endblock %}

templates/detail.html
{% extends 'base.html' %}

{% block body %}

 <div class="card shadow mt-2">
        <div class="card-body">
          <h5 class="card-title">{{ task.name }}</h5>
          <p><b>{{ task.priority }}</b></p>
          <p><b>{{ task.date }}</b></p>
          <a class="btn btn-danger" href="{% url 'todoapp:delete' task.id %}">Done</a>
          <a class="btn btn-warning" href="{% url 'todoapp:update' task.id %}">Update</a>
        </div>
      </div>


{% endblock %}

templates/edit.html
{% extends 'base.html' %}

{% block body %}

<form method="post">
    {% csrf_token %}
    {{ f.as_p }}
    <input type="submit">
</form>


{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block body %}


<div class="container">
  <div class="row">
    <div class="col-6">
      <form class="shadow p-3" method="post">
        {% csrf_token %}
        <h3>Add Your Tasks</h3>
        <label for="username" class="form-label mt-3">Your user name</label>
        <input type="text" class="form-control" id="username" name="username" required>
        <label for="task" class="form-label">Task Name</label>
        <input type="text" class="form-control" id="task" name="task">
        <label for="priority" class="form-label">Priority</label>
        <input type="number" class="form-control" id="priority" name="priority">
        <label for="date" class="form-label">Date</label>
        <input type="date" class="form-control" name="date" id="date">
        <button type="submit" class="btn btn-primary my-3">Submit</button>
      </form>
    </div>

    <div class="col-6 mt-2">
      <h3>Tasks to be completed...</h3>
      {% for i in task %}
      <div class="card shadow mt-2">
        <div class="card-body">
          <h5 class="card-title">{{ i.name }}</h5>
          <p><b>{{ i.priority }}</b></p>
          <p><b>{{ i.date }}</b></p>
          <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Done</a>
          <a class="btn btn-warning" href="{% url 'todoapp:update' i.id %}">Update</a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

templates/update.html
{% extends 'base.html' %}

{% block body %}

<div class="card">
  <div class="card-header">
    <div class="card-title">
      Task update
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
      </form>

    </div>
  </div>
</div>




{% endblock %}